"""new

Revision ID: 3a22dadf03cf
Revises: eaee6dbf6d94
Create Date: 2026-05-02 21:33:07.958080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a22dadf03cf'
down_revision = 'eaee6dbf6d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_postcode', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_subscribed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscribed', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('delivery_postcode')
        batch_op.drop_column('delivery_city')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_name')

    # ### end Alembic commands ###
