"""add car details fields

Revision ID: 5d87ddf49d21
Revises: 0840b221f6bc
Create Date: 2026-04-29 19:11:04.087870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d87ddf49d21'
down_revision = '0840b221f6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gearbox', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('engine_size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('doors', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('doors')
        batch_op.drop_column('engine_size')
        batch_op.drop_column('gearbox')
        batch_op.drop_column('fuel_type')

    # ### end Alembic commands ###
