"""expiry

Revision ID: e0a0dcb1a962
Revises: 4ef3f73ab34f
Create Date: 2026-05-05 01:10:30.692427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a0dcb1a962'
down_revision = '4ef3f73ab34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')

    # ### end Alembic commands ###
